name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */6 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    name: Jobs to update datas
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Snake Animation
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/grid-snake.svg?palette=github-light
            dist/grid-snake-dark?palette=github-dark
            dist/grid-snake-pink-light.svg?palette=github-light&color_snake=#FF2266&color_dots=#EBEDF0,#22C7FF,#47ADF9,#7190E8,#9270CA
            dist/grid-snake-pink-dark.svg?palette=github-dark&color_snake=#FF2266&color_dots=#161B22,#22C7FF,#47ADF9,#7190E8,#9270CA

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
